import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "Dog Breeds",
  description: "Generated by create next app",
};

import {Suspense} from "react";

import {CardDogSkeleton} from "../ui/skeleton/CardDogSkeleton";
import {CardDog} from "../ui/components/CardDog";

import {getDogByBreed, getMultipleRandomDogs} from "@/services";

export default async function Page({params}: {params: {breed: string}}) {
  const listDogs = params.breed ? await getDogByBreed(params.breed) : await getMultipleRandomDogs();

  if (listDogs.status !== "success") {
    return <div className="py-8">No se encontró a la raza: {params.breed}</div>;
  }

  return (
    <section className="m-auto w-full py-8">
      <Suspense
        fallback={
          <div className="grid grid-cols-3 gap-4 py-8">
            {Array.from({length: 10}).map((_, index) => (
              <CardDogSkeleton key={index!} />
            ))}
          </div>
        }
      >
        <div className="grid grid-cols-3 gap-4 py-8">
          {listDogs.dogs.slice(0, 10).map((dog) => (
            <CardDog key={dog.id} dog={dog.url} />
          ))}
        </div>
      </Suspense>
    </section>
  );
}
