import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Hello Extend Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container m-auto grid min-h-screen grid-rows-[auto,1fr,auto] px-4 font-sans antialiased">
        <header className="font-bold leading-[4rem]">Hello Extend Challenge</header>
        <main className="py-8">{children}</main>
        <footer className="text-center leading-[4rem] opacity-60">
          By ©Kevoff {new Date().getFullYear()}
        </footer>
      </body>
    </html>
  );
}
