import type {Metadata} from "next";

import Link from "next/link";

import "./globals.css";

import {Search} from "./ui/components/Search";
import FavoriteProvider from "./favorites-provider";

import {HeartIcon} from "@/assets/icons";

export const metadata: Metadata = {
  title: "Dog Breeds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-auto grid min-h-screen max-w-5xl grid-rows-[auto,1fr,auto] px-4 font-sans antialiased">
        <header className="mt-6 flex items-center justify-between text-2xl font-bold leading-[4rem]">
          <Link href="/">Dog Breeds</Link>
          <Link href="#favorites">
            <HeartIcon color="red" />
          </Link>
        </header>
        <main>
          <Search />
          <FavoriteProvider>{children}</FavoriteProvider>
        </main>
        <footer className="text-center leading-[4rem] opacity-60">
          By ©Kevoff {new Date().getFullYear()}
        </footer>
      </body>
    </html>
  );
}
